language: python
python: 3.7.2
dist: xenial
install:
  - pip install -r requirements.txt
  - pip install .
jobs:
  include:
    - stage: Unit Tests With Coverage
      script: pytest --cov=clashboard --cov-fail-under=90
    - stage: Style Check
      script pycodestyle src tests
